---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Prerequisites
      apt: name={{ item }} state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx', 'mysql-client', 'php-fpm', 'php-curl', 'php-mysql' , 'php-gd', 'php-intl', 'php-mbstring', 'php-soap', 'php-xml', 'php-xmlrpc', 'php-zip' ]

    - name: Creates directory
      file:
        path: /gluster
        state: directory
        mode: 0755            

    - name: Copies the bash script
      template:
        src: "files/bash.j2"
        dest: "/home/bash.sh"

    - name: Execute the script
      command: sh /home/bash.sh

# Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/silviuebinca.ro"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/silviuebinca.ro"
        dest: "/etc/nginx/sites-enabled/silviuebinca.ro"
        state: link
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Sets the server value
      template:
        src: "files/index.j2"
        dest: "/var/www/index.html"
   
    - name: Restart nginx
      service: name=nginx state=restarted enabled=yes
      
      
- hosts: loadbalancer
  become: true
  tasks:
    - name: Updates the loadbalancer file
      template:
        src: "files/default.j2"
        dest: "/etc/nginx/sites-available/default"
   
    - name: restart nginx
        service: name=nginx state=restarted enabled=yes
